#!/bin/sh

# Welcome to a fork of the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

create_folder_if_not_there() {
  local folder="$1"

  if [ -d "$folder" ]; then
    if ! [ -r "$folder" ]; then
      sudo chown -R "$LOGNAME:admin" "$folder"
    fi
  else
    sudo mkdir -p "$folder"
    sudo chflags norestricted "$folder"
    sudo chown -R "$LOGNAME:admin" "$folder"
  fi
}

is_app_installed() {
    local appNameOrBundleId=$1 bundleId

    # convert app name to bundle ID
    bundleId=$(osascript -e "id of application \"$appNameOrBundleId\"" 2>/dev/null) || { return 1; }

    # search for location of app with given bundle ID
    osascript -e "tell application \"Finder\" to POSIX path of (get application file id \"$bundleId\" as alias)" 2>/dev/null || { return 1; }
}

install_gui_app() {
  local appName="$1" caskName="$2"

  is_app_installed "$appName"
  if [ $? -eq 1 ]; then
    brew install --cask "$caskName"
  fi
}


# Check for Terminal running in ARM mode, install Rosetta, exit script
ARCH=$(arch)
if [[ "$ARCH" == "arm64" ]]; then
    /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    fancy_echo "\e[1;34m *** CodeClan - \e[1;31mAdditional manual steps required please visit - \033[0m"
    fancy_echo "https://github.com/codeclan/laptop/blob/master/apple_silicon.md"
    fancy_echo ""
    exit 0
fi

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"
create_folder_if_not_there "$HOMEBREW_PREFIX"

case "$SHELL" in
  */zsh) : ;;
  *)
    fancy_echo "Changing your shell to zsh ..."
      chsh -s "$(which zsh)"
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
    rbenv rehash
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list --formula | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "homebrew/cask-fonts"

# Unix
brew "git"
brew "zsh"
brew "tree"

# Programming languages
brew "node"

fancy_echo "Installing Oh-My-Zsh ..."
curl -L \
  "https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh" | sh


fancy_echo "Installing GUI apps"

# VSCode
install_gui_app "visual studio code" "visual-studio-code"
cat << EOF >> ~/.zshrc
# Add Visual Studio Code (code)
export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

fancy_echo "Skipping rdoc generation when we install a gem"
echo 'gem: --no-rdoc --no-ri' >> ~/.gemrc

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

fancy_echo "Globally ignoring .DS_Store files"
echo .DS_Store >> ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
git config --global init.defaultBranch main

fancy_echo "Checking for unsuccessful installs"

curl --remote-name "https://raw.githubusercontent.com/CrugBarat/ANDigital-onboarding-mac-setup/develop/laptop_install_test"
sh laptop_install_test

fancy_echo "Beep bop boop - script has finished 😎 "
